[package]
name = "functional-rust"
version = "1.0.0"
authors = ["Sasaki Touma"]
description = "Library for functional programming in Rust"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
